name: Assemble all subprojects

on: push

jobs:
  assemble-all-subprojects:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Check out the code
        uses: actions/checkout@v2

      - name: Assemble all subprojects
        run: ./gradlew assembleAll
